title: Cheng-Jun Kang
email: re6144051@gs.ncku.edu.tw
baseurl: ""
url: "https://cjkang0601.github.io"
github_username: CJKang0601
description: >
  Master's student in Data Science,
  focusing on Computer Vision and Multimodal Learning.

linkedin_username: cheng-jun-kang
